apiVersion: template.openshift.io/v1
kind: Template
metadata:
  creationTimestamp: null
  name: echo-api
  annotations:
    description: "3scale Echo API"
    iconClass: "icon-ruby"
    tags: "api,echo-api,3scale"
  labels:
    app: echo-api

objects:

- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: echo-api
    labels:
      app: echo-api
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: echo-api
    strategy:
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 180
        updatePeriodSeconds: 1
      type: RollingUpdate
    template:
      metadata:
        labels:
          app: echo-api
      spec:
        containers:
        - image: ${ECHOAPI_IMAGE}
          imagePullPolicy: Always
          name: echo-api
          livenessProbe:
            tcpSocket:
              port: 9292
            initialDelaySeconds: 10
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /test/200
              port: 9292 
            initialDelaySeconds: 15
            timeoutSeconds: 1
          ports:
          - containerPort: 9292
            protocol: TCP

- apiVersion: v1
  kind: Service
  metadata:
    name: echo-api
    labels:
      app: echo-api
  spec:
    ports:
    - name: echo-api-port
      port: 80
      protocol: TCP
      targetPort: 9292
    selector:
      app: echo-api

- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    name: echo-api
    labels:
      app: echo-api
  spec:
    host: ${ECHOAPI_HOST}
    to:
      kind: Service
      name: echo-api
    port:
      targetPort: echo-api-port
    tls:
      termination: edge
      insecureEdgeTerminationPolicy: Allow

parameters:
- name: ECHOAPI_IMAGE
  description: "Docker image to the Echo API"
  value: "quay.io/3scale/echoapi:stable"
  required: true

- name: ECHOAPI_HOST
  description: "Host for the Route Object"
  required: true
