version: 2
jobs:
  build:
    working_directory: /home/circleci/echo-api
    docker:
      - image: cimg/ruby:3.3
        environment:
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          OPENTRACING_TRACER: jaeger
          BUNDLE_FROZEN: true # --deployment
      - image: quay.io/jaegertracing/jaeger:2.4.0
        environment:
          COLLECTOR_OTLP_ENABLED: 1
    steps:
      - checkout

      - restore_cache:
          keys:
            - echo-api-v1-bundle-{{ arch }}-{{ checksum "Gemfile.lock" }}

      - run:
          name: Bundle Install
          command: gem install -N bundler && (bundle check || bundle install)

      - save_cache:
          key: echo-api-v1-bundle-{{ arch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: Start Echo API
          command: |
            bundle exec rackup --port 3000 --host 0.0.0.0 --env production
          background: true

      - run:
          name: Smoke test Echo API
          command: |
            dockerize -wait tcp://localhost:16686 -timeout 1m # wait for jaeger
            dockerize -wait tcp://0.0.0.0:3000 -timeout 1m # wait for echo-api

            curl --fail http://0.0.0.0:3000/test
            [ x204 = x`curl -s -o /dev/null -w "%{http_code}" http://0.0.0.0:3000/status/204` ]

      - run:
          name: Verify OpenTracing
          command: |
            sleep 11 # default flush timeout is 10 https://github.com/open-telemetry/opentelemetry-ruby/tree/main/exporter/otlp-http
            curl -sS http://localhost:16686/api/services/echo-api/operations | tee operations.out
            jq '(.data | length) > 0' --exit-status < operations.out

