version: 2
jobs:
  build:
    working_directory: /home/circleci/echo-api
    docker:
      - image: circleci/ruby:2.7
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          OPENTRACING_TRACER: jaeger
          BUNDLE_FROZEN: true # --deployment
      - image: jaegertracing/all-in-one:1.21
        environment:
          COLLECTOR_ZIPKIN_HTTP_PORT: 9411
    steps:
      - checkout

      - restore_cache:
          keys:
            - echo-api-v1-bundle-{{ arch }}-{{ checksum "Gemfile.lock" }}

      - run:
          name: Bundle Install
          command: gem install -N bundler && (bundle check || bundle install)

      - save_cache:
          key: echo-api-v1-bundle-{{ arch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: Start Echo API
          command: |
            bundle exec rackup --port 3000 --host 0.0.0.0 --env production
          background: true

      - run:
          name: Smoke test Echo API
          command: |
            dockerize -wait tcp://localhost:16686 -timeout 1m # wait for jaeger
            dockerize -wait tcp://0.0.0.0:3000 -timeout 1m # wait for echo-api

            curl --fail http://0.0.0.0:3000/test

      - run:
          name: Verify OpenTracing
          command: |
            sleep 1 # that is the flush timeout
            curl http://localhost:16686/api/services/echo-api/operations | jq '(.data | length) > 0' --exit-status

