openapi: "3.0.0"
info:
  title: Echo API
  description: Simple Rest API that returns back info about the request.
  version: "1.0.0"
servers:
  - url: '{protocol}://echo-api.3scale.net'
    variables:
      protocol:
        enum:
          - https
          - http
        default: https
paths:
  /{requestPath}:
    summary: Wildcard Path
    description: Wildcard Path which will echo any given path.
    parameters:
      - $ref: '#/components/parameters/requestPath'
      - $ref: '#/components/parameters/requestArgument'
      - $ref: '#/components/parameters/requestBody'
    get:
      tags:
        - wildcard path
      responses:
        '200':
          $ref: "#/components/responses/echo"
    put:
      tags:
        - wildcard path
      responses:
        '200':
          $ref: "#/components/responses/echo"
    post:
      tags:
        - wildcard path
      responses:
        '200':
          $ref: "#/components/responses/echo"
    delete:
      tags:
        - wildcard path
      responses:
        '200':
          $ref: "#/components/responses/echo"
    options:
      tags:
        - wildcard path
      responses:
        '200':
          $ref: "#/components/responses/echo"
    head:
      tags:
        - wildcard path
      responses:
        '200':
          $ref: "#/components/responses/echo"
    patch:
      tags:
        - wildcard path
      responses:
        '200':
          $ref: "#/components/responses/echo"
  /status/{statusCode}:
    summary: Set the HTTP Status Code for the echoed response.
    description: Generates a HTTP response with a give {statusCode} parameter.
    parameters:
      - $ref: '#/components/parameters/statusCode'
      - $ref: '#/components/parameters/requestArgument'
      - $ref: '#/components/parameters/requestBody'
    get:
      tags:
        - status code
      responses:
        default:
          $ref: "#/components/responses/echo"
    put:
      responses:
        default:
          $ref: "#/components/responses/echo"
    post:
      responses:
        default:
          $ref: "#/components/responses/echo"
    delete:
      responses:
        default:
          $ref: "#/components/responses/echo"
    options:
      responses:
        default:
          $ref: "#/components/responses/echo"
    head:
      responses:
        default:
          $ref: "#/components/responses/echo"
    patch:
      responses:
        default:
          $ref: "#/components/responses/echo"
components:
  responses:
    echo:
      description: Default request response
      content:
        'application/json':
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Echo'

        'application/xml':
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Echo'
  parameters:
    requestArgument:
      name: requestArgument
      in: query
      description: Argument used in the request.
      required: false
      schema:
        type: string
    requestPath:
      name: requestPath
      in: path
      description: Path to be echoed.
      required: true
      schema:
        type: string
    statusCode:
      name: statusCode
      in: path
      description: HTTP Status Code to be echoed. Must be between 200 and 599.
      required: true
      schema:
        type: integer
        minimum: 200
        maximum: 599
    requestBody:
      name: requestBody
      in: body
      description: HTTP Request Body.
      required: false
      schema:
        type: string
  schemas:
    Echo:
      type: object
      properties:
        method:
          type: string
          description: HTTP Method used in the original request.
        path:
          type: string
          description: Path url used in the original request.
        argument:
          type: string
          description: Argument used in the original request.
        body:
          type: string
          description: Body used in the original request.
        headers:
          type: array
          items:
            type: object
          description: HTTP Headers used in the original request.
        uuid:
          type: string
          format: uuid
          description: Image URL representing the product.
